// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteEntry(ctx context.Context, id int64) error
	DeleteTransfer(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfersFromAccount(ctx context.Context, arg ListTransfersFromAccountParams) ([]Transfer, error)
	ListTransfersInvolvingAccount(ctx context.Context, arg ListTransfersInvolvingAccountParams) ([]Transfer, error)
	ListTransfersToAccount(ctx context.Context, arg ListTransfersToAccountParams) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateEntryAccount(ctx context.Context, arg UpdateEntryAccountParams) (Entry, error)
	UpdateEntryAmount(ctx context.Context, arg UpdateEntryAmountParams) (Entry, error)
	UpdateTransferAmount(ctx context.Context, arg UpdateTransferAmountParams) (Transfer, error)
	UpdateTransferFromAccount(ctx context.Context, arg UpdateTransferFromAccountParams) (Transfer, error)
	UpdateTransferToAccount(ctx context.Context, arg UpdateTransferToAccountParams) (Transfer, error)
}

var _ Querier = (*Queries)(nil)
